version: '3'
services:

  singleframephp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php8container
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
      - "443:443"
